name: Update event

on:
  watch:
    types: started
  schedule:
    - cron:  '0 0 */1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - name: Running
      run: php index.php
    - name: Commit and push
      run: |-
        git config --global user.email "bot@github.com" && git config --global user.name "Bot"
        git diff
        git add -A && git commit -m ":memo: UPDATE" || exit 0
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
