name: Pull

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Running
      run: php index.php
    - name: Commit and push
      run: |-
        git config --global user.email "zhuchunshu@dog87.com" && git config --global user.name "zhuchunshu"
        git diff
        git add -A && git commit -m ":memo: UPDATE" || exit 0
        git push

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
